### ISSUE TITLE
Authorization Type/Member Expression Exception Handling

### ISSUE THREAD

**Issue by thomasjedstrom** [asemio/otto-the-geek#27]
Greetings, really appreciate this library.  For the authorization would it be possible to add documentation for applying auth on the GraphTypeBuilder instead of just fields on the SchemaBuilder?  Also better exception handling for failing to pass a memberExpression to the Authorize method.

```c#
        protected override SchemaBuilder ConfigureSchema(SchemaBuilder builder)
        {
            return LoadConfigurators(GetType().Assembly, builder)
                .GraphType<Employee>(thingBuilder =>
                    thingBuilder.Authorize(thing => thing)
                        .Via<User>(x => x.CanListEmployees));
        }
```
^^^ this fails due to line 16 being a typeExpression (trying to authorize the Employee object holistically)

```
Error Message:
   System.InvalidCastException : Unable to cast object of type 'System.Linq.Expressions.TypedParameterExpression' to type 'System.Linq.Expressions.MemberExpression'.
  Stack Trace:
     at OttoTheGeek.Internal.ExpressionExtensions.PropertyInfoForSimpleGet[T,TProp](Expression`1 expr)
   at OttoTheGeek.Internal.GraphTypeConfiguration`1.ConfigureField[TProp](Expression`1 propExpr, Func`2 configTransform)
   at OttoTheGeek.Internal.Authorization.AuthorizationBuilder`2.Via[TAuth](Func`2 authorizeCallback)
   at Wolfkrow.Server.Employees.EmployeesConfigurator.Configure(GraphTypeBuilder`1 builder) in /Users/ThomasJamesEdstrom/Code/TopoGraphic/topographic-wolfkrow/src/backend/Wolfkrow.Server/Employees/EmployeesConfigurator.cs:line 11
   at OttoTheGeek.SchemaBuilder.GraphType[TType](Func`2 configurator)
   at OttoTheGeek.Internal.ConfiguratorAdapter`2.Configure(SchemaBuilder builder)
   at OttoTheGeek.OttoModel`3.<>c.<LoadConfigurators>b__2_6(SchemaBuilder b, ConfiguratorAdapter adapter)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at OttoTheGeek.OttoModel`3.LoadConfigurators(Assembly assembly, SchemaBuilder builder)
   at Wolfkrow.Server.GraphQlModel.ConfigureSchema(SchemaBuilder builder) in /Users/ThomasJamesEdstrom/Code/TopoGraphic/topographic-wolfkrow/src/backend/Wolfkrow.Server/GraphQlModel.cs:line 10
   at OttoTheGeek.OttoModel`3.BuildOttoSchema(IServiceCollection services)
   at OttoTheGeek.ServiceCollectionExtensions.AddOtto[TModel](IServiceCollection services, TModel model)
   at Wolfkrow.Server.Startup.ConfigureServices(IServiceCollection services) in /Users/ThomasJamesEdstrom/Code/TopoGraphic/topographic-wolfkrow/src/backend/Wolfkrow.Server/Startup.cs:line 38
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()
   at Wolfkrow.Tests.CreatingCustomersTests..ctor() in /Users/ThomasJamesEdstrom/Code/TopoGraphic/topographic-wolfkrow/src/backend/Wolfkrow.Tests/CreatingCustomersTests.cs:line 18
```
^^^ which leads to this

```c#
    public sealed class EmployeesConfigurator
        : IGraphTypeConfigurator<GraphQlModel, QueryModel>,
        IGraphTypeConfigurator<GraphQlModel, Employee>
    {
        public GraphTypeBuilder<QueryModel> Configure(GraphTypeBuilder<QueryModel> builder)
        {
            return builder
                .LooseListField(x => x.Employees)
                    .ResolvesVia<EmployeeListResolver>()
                        .Authorize(x => x.Employees)
                            .Via<GraphQLAuthorizer>(x => x.CanListEmployees());
        }

        public GraphTypeBuilder<Employee> Configure(GraphTypeBuilder<Employee> builder)
        {
            return builder.IgnoreProperty(x => x.Id);
        }
    }
}
```
^^^ as compared to this which works

**Comment by floyd-may** [comment]
Split into #28, #29, #30
